### ISSUE TITLE
`paidEventHandler` called twice at the same time

### ISSUE THREAD

**Issue by kvukusic** [PubMatic/ios-openwrap-sdk-samples#6]
In `BannerViewController` the following code:

```
override func viewDidLoad() {
        super.viewDidLoad()
        
        let adSizes = [NSValueFromGADAdSize(GADAdSizeBanner)]
        
        // Create a banner custom event handler for your ad server. Make
        // sure you use separate event handler objects to create each interstitial
        // For example, The code below creates an event handler for DFP ad server.
        let eventHandler: DFPBannerEventHandler = DFPBannerEventHandler(adUnitId: dfpAdUnit, andSizes: adSizes)

        eventHandler.configBlock = { bannerView, request, _ in
            bannerView?.paidEventHandler = { gadAdValue in
                print("\(Date())")
            }
        }

        // Create a banner view
        // For test IDs refer - https://community.pubmatic.com/display/IDFP/Test+and+debug+your+integration
        self.bannerView = POBBannerView(publisherId: pubId, profileId: profileId, adUnitId: owAdUnit, eventHandler: eventHandler)
        
        // Set the delegate
        self.bannerView?.delegate = self


        // Add the banner view to your view hierarchy
        addBannerToView(banner: self.bannerView!, adSize: GADAdSizeBanner.size)
        
        // Load Ad
        self.bannerView?.loadAd()
    }
```

`paidEventHandler` is triggered multiple times at the same instant. 
Which is not the expected behavior.
When using Google directly, paid event handler is called correctly.

**Comment by dvasko** [comment]
@pm-preety-narvekar could you give us any update on this?

**Comment by pm-preety-narvekar** [comment]
Hi @dvasko, @kvukusic 

Thanks for your notifying the issue.

It is reproducible when both OpenWrap and GAM's refresh is enabled. As per the OpenWrap's document below, GAM's refresh should be disabled and should be enabled at OpenWrap, otherwise, it will cause the inconsistent behaviour. Please check point 2 in:
https://community.pubmatic.com/display/IDFP/Show+banner+ads#Showbannerads-Showabannerad

Could you confirm if you can reproduce it after disabling refresh on GAM side?

Thanks,
Preety

**Comment by pm-preety-narvekar** [comment]
Closing it as no response is received from the reporter. Feel free to reopen if you need any more details.
Thank you!
